### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by victor-yacovlev** [mipt-proglang-2015/prolands_vakhranev#1]
```
Traceback (most recent call last):
  File "../fwalg.py", line 122, in <module>
    main(sys.argv[1:])
  File "../fwalg.py", line 114, in main
    c_floyd_warshall_from_xml_to_csv(argv[0], argv[1])
  File "../fwalg.py", line 104, in c_floyd_warshall_from_xml_to_csv
    matr = fwalg.form_resistance_matrix(form_nodes_list(tree), form_edges_list(tree))
AttributeError: 'module' object has no attribute 'form_resistance_matrix'
```

**Comment by Anton22255** [comment]
@victor-yacovlev 
Возможно была проблема с импортом.(Не смог воспроизвести на Ubuntu 14.04 )
выполнял   python3 task.py input.xml output.csv 
Переименовал файл fwalg.py в task.py и изменил название метода в ModuleMethods. 
Пожалуйста, проверьте
